### ISSUE TITLE
Getting Error - java.lang.NullPointerException: Cannot read the array length because "<local15>" is null

### ISSUE THREAD

**Issue by prasharm39** [ravi-anthapu/Neo4JQueryProcessor#1]
I'm trying to analyze Neo4J logs using jar file through cmd, so with the help of jar file running through cmd, logs files generates query_db files which we can analyze in db visualizer. 
But while running this command - **"java -jar ..\Neo4JQueryProcessor-1.4.1.jar config.yaml"** getting this error - java.lang.NullPointerException
at com.neo4j.query.QueryAnalyzer.process(QueryAnalyzer.java:65)
at com.neo4j.query.QueryAnalyzer.main(QueryAnalyzer.java:128)

**Comment by prasharm39** [comment]
I'm using "Neo4JQueryProcessor-1.4.1" version of jar file, we are Neo4J 4 version.

**Comment by ravi-anthapu** [comment]
@prasharm39 Can you please share your config.yaml file? Also, can you please try with latest jar? I have fixed few issues with parsing the log file.

**Comment by prasharm39** [comment]
Hi @ravi-anthapu , Now I'm getting below error:
Ignoring file as does not match the filter : config.yaml
<img width="641" alt="image" src="https://github.com/user-attachments/assets/8e9760f1-68d0-4f8e-8873-7d06e74aa66b">

**Comment by prasharm39** [comment]
Here is the config file details:
logType: formatted
storeType: sqlite
queryLocation: "C:\\Neo4jLogAnalyzer\\Logs\\"
fileFilter: ^query.*\.log.*$
databaseURI: jdbc:sqlite:query_db.db
defaultRuntime: pipelined

**Comment by ravi-anthapu** [comment]
@prasharm39 It seems there is a bit of nuance in this file that is not handled correctly. Would it be possible to share the query.log to see where it is failing?

Thanks
